Repository ament/ament_tools, pull requests merged in 2018-02, with the labels that each got.

#176 Pandering to finicky CMake Initial Cache ordering
  ament_tools/build_types/cmake.py
Labels: bug, in review

#177 Exclude test.* during install.
  setup.py
Labels: bug, enhancement, in review

#178 separate loops for evaluating conditions and extracting group members
  ament_tools/topological_order.py
Labels: in review
